### ISSUE TITLE
CECCE School Import

### ISSUE THREAD

**Issue by james2432** [osmottawa/imports#1]
@DenisCarriere 
http://overpass-turbo.eu/s/imO
Postal codes should have a space in the middle and I think it's part of Canada's "best practices"

**Comment by DenisCarriere** [comment]
Just fixed it :)

https://github.com/osmottawa/imports/commit/8b5a316262ba2fe60d354ff163c41fd2c0811ecd

This GitHub workflow is a lot better then gist

@james2432

**Comment by james2432** [comment]
@DenisCarriere Seem good now
