### ISSUE TITLE
Fix `addr:street` to english

### ISSUE THREAD

**Issue by DenisCarriere** [osmottawa/imports#2]
Replace abbreviated suffix and make sure field is in English (French names can be another task)

**Comment by james2432** [comment]
Fixed french translation @DenisCarriere

**Comment by DenisCarriere** [comment]
@james2432 Sweet! Now we just need to decide on Tabs vs. Spaces, lol!

**Comment by james2432** [comment]
Sorry, you had assigned it to me so I was working on it at the same time :P @DenisCarriere

**Comment by DenisCarriere** [comment]
@james2432 You were too fast to edits, merging conflicting commits is a pain. I feel ya!
